steps:
## API
# Build the container image
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=dockerfiles/model_api.dockerfile
  - --destination=eu.gcr.io/$PROJECT_ID/api:latest
  - --cache=true
  - --cache-ttl=6h
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/api:latest']
# Deploy container image to Cloud Run
- name: 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'leaf-shapes'
  - '--image'
  - 'eu.gcr.io/$PROJECT_ID/api:latest'
  - '--region'
  - 'europe-west1'
  - '--allow-unauthenticated'
  - '--memory 4G'

## TRAINING
# Build the container image
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=dockerfiles/train_model.dockerfile
  - --destination=eu.gcr.io/$PROJECT_ID/train:latest
  - --cache=true
  - --cache-ttl=6h
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/train:latest']

options:
  machineType: 'E2_HIGHCPU_8'
