name: Train Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Training Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u linneahj --password-stdin docker.io
        echo docker build . --file dockerfiles/train_model.dockerfile --tag linneahj/02476_leaf_project:$(date +%s)
        docker build . --file dockerfiles/train_model.dockerfile --tag linneahj/02476_leaf_project:$(date +%s)
        echo docker push linneahj/02476_leaf_project:$(date +%s)
        docker push linneahj/02476_leaf_project:$(date +%s)
